"""Try this

Revision ID: 1d1511b77417
Revises: None
Create Date: 2013-09-22 05:41:17.949989

"""

# revision identifiers, used by Alembic.
revision = '1d1511b77417'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historic_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urban_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('direction', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('museum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Unicode(), nullable=True),
    sa.Column('webpage', sa.String(), nullable=True),
    sa.Column('schedule', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('museum')
    op.drop_table('urban_site')
    op.drop_table('historic_site')
    op.drop_table('landmark')
    ### end Alembic commands ###
