"""Fix guid

Revision ID: 2cd1091b3b54
Revises: 1d1511b77417
Create Date: 2013-09-22 06:49:36.757609

"""

# revision identifiers, used by Alembic.
revision = '2cd1091b3b54'
down_revision = '1d1511b77417'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmark', sa.Column('guid', sa.String(), nullable=True))
    op.add_column('museum', sa.Column('phone', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('museum', 'phone')
    op.drop_column('landmark', 'guid')
    ### end Alembic commands ###
