"""Add guid to landmarks

Revision ID: 56ccd2fbf4aa
Revises: 1d1511b77417
Create Date: 2013-09-22 05:54:59.036464

"""

# revision identifiers, used by Alembic.
revision = '56ccd2fbf4aa'
down_revision = '1d1511b77417'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmark', sa.Column('guid', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landmark', 'guid')
    ### end Alembic commands ###
