"""Add architecture type

Revision ID: 57654804b33a
Revises: 2cd1091b3b54
Create Date: 2013-09-22 08:26:24.731079

"""

# revision identifiers, used by Alembic.
revision = '57654804b33a'
down_revision = '2cd1091b3b54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urban_site', sa.Column('arch_type', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urban_site', 'arch_type')
    ### end Alembic commands ###
