"""Foreign key added.

Revision ID: 59d7e2054945
Revises: 154d210ee5e7
Create Date: 2013-09-21 22:17:27.125907

"""

# revision identifiers, used by Alembic.
revision = '59d7e2054945'
down_revision = '154d210ee5e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmark', sa.Column('kind_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landmark', 'kind_id')
    ### end Alembic commands ###
